[Seat:*]
# Explicitly call the X server (XLibre replaces xorg-server binary at /usr/bin/X)
xserver-command=/usr/bin/X -nolisten tcp

# Set the greeter (installed in packages.x86_64)
greeter-session=lightdm-gtk-greeter

# Autologin for Live ISO
autologin-user=bluebyte
autologin-user-timeout=0

# Wrapper
session-wrapper=/etc/lightdm/Xsession   
